### PR TITLE
feat: add support for Capacitor 3

### PR DESCRIPTION
**Pull request by NunoSav**
resolves https://github.com/capacitor-community/keep-awake/issues/6

### CODE REVIEW

**Comment by NunoSav** [comment]
Forgot to change version on one file but it's done now.
@Boosten when can i expect a release?

Thanks.

**Comment by NunoSav** [comment]
@Boosten please review my changes and give me some feedback.

**Comment by Boosten** [comment]
I will take a look upcoming days. Thanks for the effort so far!

**Comment by NunoSav** [comment]
Any news?

**Comment by Boosten** [comment]
@NunoSav  I think it's better to wait for the official Capacitor 3.0 release so we do not have to reference beta versions in the package.json. 
Let's use this PR to eventually upgrade to 3.0.

Besides that, I think we also need to update the Android Configuration step: https://github.com/capacitor-community/keep-awake#android Because adding plugins in the MainActivity is not required anymore, right?

**Comment by NunoSav** [comment]
> @NunoSav I think it's better to wait for the official Capacitor 3.0 release so we do not have to reference beta versions in the package.json.
> Let's use this PR to eventually upgrade to 3.0.
Understood.

> Besides that, I think we also need to update the Android Configuration step: https://github.com/capacitor-community/keep-awake#android Because adding plugins in the MainActivity is not required anymore, right?
Yes, you're right, you can reference [this](https://capacitorjs.com/docs/v3/updating/3-0#switch-to-automatic-android-plugin-loading) if you like.

**Comment by Boosten** [comment]
Thanks for the effort @robingenz 🎉

**Pull request merged**
