### PR TITLE
fix(web): keep app awake after returning from the background

### PR DESCRIPTION
**Pull request by sabereen**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] The changes have been tested successfully.

### CODE REVIEW

**Comment by robingenz** [comment]
What problem does this PR solve?

**Comment by sabereen** [comment]
Hello.

1. In SSR compatible projects, we cannot use web-only APIs directly (etc. navigator). So, such projects cannot use this plugin.
2. On the web, when the app is sent to the background, the WakeLock is released, and after returning to the app, we need to request the WakeLock again.

**Comment by robingenz** [comment]
So you are fixing two problems with this PR. Please create two separate PRs for this so that the automatically generated changelog remains clear.

**Comment by sabereen** [comment]
I reverted the commit related to SSR compatibility, and now this PR only does one thing.

**Comment by robingenz** [comment]
Please run "npm run fmt" to format the code.

**Comment by sabereen** [comment]
done

**Review by robingenz — APPROVED** [review]
Thank you!

**Pull request merged**
